webny_unav.settings:
  type: mapping
  label: 'NYS uNav'
  mapping:
    webny_unav:
      type: mapping
      mapping:
        webny_unav_auto:
          type: text
          label: 'uNav automatic insertion'
        webny_alt_unav_auto:
          type: text
          label: 'alt uNav automatic insertion'
        webny_alt_unav_translate:
          type: text
          label: 'alt uNav translate'
        webny_alt_unav_search:
          type: text
          label: 'alt uNav search'
        webny_alt_unav_search_client:
          type: text
          label: 'alt uNav search client'
        webny_alt_unav_search_collection:
          type: text
          label: 'alt uNav search collection'